/*
 * This Spock specification was generated by the Gradle 'init' task.
 */
package hello_09

import spock.lang.Specification

import com.work.hello.*

class AppTest extends Specification {
    def "application has a greeting"() {
        setup:
        def app = new App()

        when:
        def result = app.greeting

        then:
        result != null
    }

    def "sum test"() {
        when:
        def x = Utils.sum(2, 5)

        then:
        x == 7
    }
}
